### ISSUE TITLE
ModuleNotFoundError: No module named 'two_sample_util' from running 'funfams_clustering_pipeline_example.py'

### ISSUE THREAD

**Issue by kyle-davis279** [Rostlab/FunFamsClustering#1]
I tried running 'funfams_clustering_pipeline_example.py'  but I received an error message:

Traceback (most recent call last):
  File "/home/kyle/Desktop/FunFamsClustering-main/funfams_clustering_pipeline_example.py", line 2, in <module>
from distance_calculator import EmbeddingDistance
  File "/home/kyle/Desktop/FunFamsClustering-main/distance_calculator.py", line 5, in <module>
    from two_sample_util import pdist
ModuleNotFoundError: No module named 'two_sample_util'

I've spent a good number of hours googling how to resolve the issue but nothing has worked. I'm new to programming but I suspect the error is due to not having the 'two_sample_util.py' file in the 'FunFamsClustering-main' folder. I've installed the program just fine but the 'two_sample_util.py' file wasn't there.

**Comment by mariasche** [comment]
Apologies for not including this file to begin with! It's part of the repo now, so the example should work.
