### ISSUE TITLE
ModuleNotFoundError: No module named 'clustering_pipeline'

### ISSUE THREAD

**Issue by kyle-davis279** [Rostlab/FunFamsClustering#2]
I ran 'funfams_clustering_pipeline_example.py' and received this error:

Traceback (most recent call last):
  File "/home/kyle/Desktop/FunFamsClustering-main/funfams_clustering_pipeline_example.py", line 4, in <module>
    from clustering_pipeline import DBSCANClustering
ModuleNotFoundError: No module named 'clustering_pipeline'

I suppose you haven't included 'clustering_pipeline.py' in the repo.

**Comment by mariasche** [comment]
Apologies that you had to run into a similar error again. I hope it works now.
